
[[redirects]]
  from = "/auth/*"
  to = "http://crm-made-simple-f8a83a9caed2.herokuapp.com/:splat"
  status = 200

[[headers]]
  for = "/auth/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
