[[redirects]]
  from = "http://localhost:3000"
  to = "http://192.168.0.101:8080"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
